services:
  - type: web
    name: agentflow-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: agentflow-redis
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

  - type: worker
    name: agentflow-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_worker.celery_app worker --loglevel=info"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: agentflow-redis
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

  - type: redis
    name: agentflow-redis
    ipAllowList: []
    plan: free
